name: Create GitHub Release
permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Create Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda
        with:
          generate_release_notes: true
