name: Create GitHub Release
permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Create Release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b
        with:
          generate_release_notes: true
