name: CI - Build KYS.AspNetCore Library
permissions:
  contents: read
  pull-requests: read

on:
  workflow_dispatch: # Allows manual trigger
  push:
    branches:
      - master
    paths:
      - "src/KYS.AspNetCore.Library/**"
      - "src/KYS.Library/**"
  pull_request:
    branches:
      - master
    paths:
      - "src/KYS.AspNetCore.Library/**"
      - "src/KYS.Library/**"

jobs:
  build:
    uses: ./.github/workflows/templates/reusable-dotnet-build.yml
    with: 
      library-name: 'KYS.AspNetCore Library'
      library-project-path: 'src/KYS.AspNetCore.Library/KYS.AspNetCore.Library.csproj'
      library-tests-project-path:
      dotnet-version: '8.0.x'
