name: Build and Publish KYS.AspNetCore.Library DocFX
permissions:
  contents: write

on:
  workflow_dispatch: # Allows manual trigger
  push:
    branches:
      - master
    paths:
      - "src/KYS.AspNetCore.Library/**"

jobs:
  build-docs:
    uses: ./.github/workflows/reusable-publish-docfx.yml
    with:
      library-name: kys-aspnetcore-library
      docfx-project: src/KYS.AspNetCore.Library/docfx
      docfx-publish-dir: ./src/KYS.AspNetCore.Library/docfx/_site
      dotnet-version:
    permissions:
      contents: write
