name: CI - Build KYS.Library
permissions:
  contents: read
  pull-requests: read

on:
  workflow_dispatch: # Allows manual trigger
  push:
    branches:
      - master
    paths:
      - "src/KYS.Library/**"
  pull_request:
    branches:
      - master
    paths:
      - "src/KYS.Library/**"

jobs:
  build:
    uses: ./.github/workflows/templates/reusable-dotnet-build.yml
    with: 
      library-name: 'KYS.Library'
      library-project-path: 'src/KYS.Library/KYS.Library.csproj'
      library-tests-project-path: 'tests/KYS.Library.Tests/KYS.Library.Tests.csproj'
      dotnet-version: '8.0.x'
