name: KYS.Library - SonarQube

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "src/KYS.Library/**"
      - "tests/KYS.Library.Tests/**"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "src/KYS.Library/**"
      - "tests/KYS.Library.Tests/**"

jobs:
  scan:
    uses: ./.github/workflows/reusable-sonar-scan.yml
    with:
      tests-project-path: "tests/KYS.Library.Tests"
      lib-project-path: "src/KYS.Library"
      sonar-project-name: "yongshun950824_kys-library"
      sonar-org: "yongshun950824"
      sonar-exclusions: "**/bin/**,**/obj/**,**/Migrations/**,**/Generated/**,**/KYS.AspNetCore.Library/**,**/KYS.EFCore.Library/**"
      sonar-coverage-exclusions: "**/KYS.AspNetCore.Library/**,**/KYS.EFCore.Library/**,**/Generated/**"
      sonar-cpd-exclusions: "**/Migrations/**,**/Generated/**"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    permissions:
      contents: read
